### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by vinkaga** [mileszim/tempmail.js#2]
I am using the following code just like in the README
```
var TempMail = require('tempmail.js');

var account = new TempMail();
account.getMail().then((messages) => {
	console.log(messages);
});
```
But that results in 
```
$ node mailtest.js
/Users/temp/mailtest.js:4
account.getMail().then((messages) => {
                 ^

TypeError: Cannot read property 'then' of undefined
    at Object.<anonymous> (/Users/temp/mailtest.js:4:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by mileszim** [comment]
Hey @vinkaga, I can't reproduce the bug you have. Are you using the latest version of tempmail.js? Should be 0.2.1

**Comment by vinkaga** [comment]
Yes it works with 0.2.1.
